sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LPM-231.pdf --upload --lsstdoc LPM-231.tex --env=travis --ltd-product $PRODUCT"
env:
  global:
    - PRODUCT="lpm-231"
    # LSST the Docs credentials
    - secure: "xxx"
    - secure: "yyy"
